-- Viza arizalari va narx tushishi obunalari
-- Supabase Dashboard -> SQL Editor orqali bir marta ishga tushiring.

begin;

create table if not exists public.visa_applications (
    id bigint generated by default as identity primary key,
    telegram_user_id bigint not null,
    username text,
    visa_type text not null check (visa_type in ('tourist_multi', 'umrah_nusuk')),
    first_name text not null check (char_length(first_name) between 2 and 80),
    last_name text not null check (char_length(last_name) between 2 and 80),
    phone text not null check (char_length(phone) between 7 and 30),
    passport_number text not null check (char_length(passport_number) between 5 and 20),
    birth_date date not null,
    travel_date date,
    notes text check (notes is null or char_length(notes) <= 1000),
    status text not null default 'new'
        check (status in ('new', 'processing', 'approved', 'rejected')),
    admin_note text check (admin_note is null or char_length(admin_note) <= 1000),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists visa_applications_user_idx
    on public.visa_applications (telegram_user_id, created_at desc);
create index if not exists visa_applications_status_idx
    on public.visa_applications (status, created_at desc);

create table if not exists public.price_alerts (
    id bigint generated by default as identity primary key,
    telegram_user_id bigint not null,
    username text,
    origin varchar(3) not null check (origin ~ '^[A-Z0-9]{3}$'),
    destination varchar(3) not null check (destination ~ '^[A-Z0-9]{3}$'),
    date_from date not null,
    date_to date not null,
    target_price numeric(10, 2) not null check (target_price > 0),
    is_active boolean not null default true,
    last_price numeric(10, 2),
    last_checked_at timestamptz,
    last_notified_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint price_alerts_date_order check (date_to >= date_from)
);

create index if not exists price_alerts_user_idx
    on public.price_alerts (telegram_user_id, created_at desc);
create index if not exists price_alerts_active_idx
    on public.price_alerts (is_active, date_from, date_to);
create unique index if not exists price_alerts_unique_active_idx
    on public.price_alerts (
        telegram_user_id, origin, destination, date_from, date_to, target_price
    ) where is_active = true;

-- updated_at ni barcha o'zgarishlarda avtomatik yangilash.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists visa_applications_set_updated_at on public.visa_applications;
create trigger visa_applications_set_updated_at
before update on public.visa_applications
for each row execute function public.set_updated_at();

drop trigger if exists price_alerts_set_updated_at on public.price_alerts;
create trigger price_alerts_set_updated_at
before update on public.price_alerts
for each row execute function public.set_updated_at();

-- Bu jadvallarga faqat backenddagi service_role kaliti kira oladi.
alter table public.visa_applications enable row level security;
alter table public.price_alerts enable row level security;

commit;
